### ISSUE TITLE
Strange case insensitivity property

### ISSUE THREAD

**Issue by rahatarmanahmed** [darkskyapp/string-hash#3]
I was using this module to get a hash and mod by 16 to get a random-ish but constant index for a given string. I was about to ensure the string was lowercase so that the hash was case insensitive, when I noticed that all my indexes for a string were the same no matter what the case was!

Here's an example on tonic to show this: https://tonicdev.com/rahat/string-hash-case-insensitivity

I noticed that this property holds true if you mod a hash by a power of 2 up to ~~64~~32 (though 64 does have a lot of matching indexes, it will rarely have a different index for a different case).

I don't know if this a bug per-se, but it is a very interesting property. Any clue as to why it behaves like this?

**Comment by rahatarmanahmed** [comment]
Nevermind! My good friend @raymond-h solved it.
```
@KR:	Because multiplication by 33 is the same as multiplication with (32 + 1), AKA (1<<5 + 1), which results in (asciiValue << 5) + (asciiValue)
@KR:	The only bit differing between uppercase and lowercase letters is the 6th bit (assuming least significant bit is the 1st bit)
@KR:	Meaning that regardless of the casing of the letters, the five lowest bits will be the same when XORing during every iteration
@KR:	And when you do modulo 2^x, you strip off all but the least x count of bits
```

**Comment by ironwallaby** [comment]
Good analysis! Yeah, I don't think this is the hash algorithm for your use-case: you might want to use something more sophisticated :)

**Comment by rahatarmanahmed** [comment]
Nah it did what I wanted (case insensitivity) before I even tried to! Thanks.
