### ISSUE TITLE
 no such file or directory, rename 

### ISSUE THREAD

**Issue by jadissa** [darkskyapp/string-hash#7]
[user@likely html]$ sudo npm install string-hash -save
npm ERR! path /var/www/html/node_modules/npm/node_modules/dezalgo
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/var/www/html/node_modules/npm/node_modules/dezalgo' -> '/var/www/html/node_modules/npm/node_modules/.dezalgo.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-10T05_45_35_903Z-debug.log

**Comment by jadissa** [comment]
Solved with 
rm package-lock.json 
npm install

centos-07

[user@likely html]$ npm --version
5.6.0
[user@likely html]$ node --version
v8.9.1

**Comment by ironwallaby** [comment]
Thanks, but it looks like this is an issue with a different package (`dezalgo`), rather than `string-hash`.
