### ISSUE TITLE
possible to unhash?

### ISSUE THREAD

**Issue by Bizarrus** [darkskyapp/string-hash#8]
It is possible to unhash the resultet value?

**Comment by ironwallaby** [comment]
It is not. (In fact, any given hash value can correspond to an infinite number of possible strings.)

This is a necessary consequence of the [pigeonhole principle](https://en.wikipedia.org/wiki/Pigeonhole_principle): there are only 2^32 possible hash values, but an infinite number of possible strings. (In fact, if you stick with printable ASCII characters, a string of length 7 is enough to guarantee a collision!)

If you need to retain the original string, using a hashing function is almost certainly the wrong tool for the job.
